# Build
FROM node:16 AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Run
FROM node:16
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/build .
CMD [ "node", "build/index.js" ]